### ISSUE TITLE
NameError: name 'unhashedDict' is not defined

### ISSUE THREAD

**Issue by evianita08** [DeivisDervinis/EAPDA#1]
Hi Dervinis!
i've tried your code and using your dataset. I've followed your EAPDA.ipynb and i found an error while running the last cell. Here is the error!

<ipython-input-42-41f4dd9d9366> in <module>()
      9 
     10 
---> 11 for item in unhashedDict:
     12   if item in segmentEmoDuration:
     13     segmentEmoDuration[item] = unhashedDict.get(item)

NameError: name 'unhashedDict' is not defined

Can you give any advice to solve this problem?

**Comment by DeivisDervinis** [comment]
Hi evianita08,

I've pushed a fix to the code that should fix the unhashedDict issue for the last cell. Colab file should be updated with the latest changes. 

The fix:
unhashedDict doesn't exist, but we can use timestampList to calculate the accuracy of each of the major emotions.
<pre>
index = 0

for item in unhashedList:
  if item in segmentEmoDuration:
    segmentEmoDuration[item] = timestampList[index]
    index += 1
</pre>

**Comment by evianita08** [comment]
Hey Dervinis!
Thanks alot. it works!

**Comment by DeivisDervinis** [comment]
Solved. Closed Issue.
